/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2024-03-05 04:56:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/member/../include/header.jsp", Long.valueOf(1709372383716L));
    _jspx_dependants.put("jar:file:/D:/gyujin/sideP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shoppiingMall/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/footer.jsp", Long.valueOf(1702642534211L));
    _jspx_dependants.put("jar:file:/D:/gyujin/sideP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shoppiingMall/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1659671595531L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>마이페이지</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/normalize.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        .mypage\r\n");
      out.write("        {\r\n");
      out.write("            margin: 100px;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage h2\r\n");
      out.write("        {\r\n");
      out.write("            font-size: 1.3em;\r\n");
      out.write("            margin: 30px 0 30px 0;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .grade \r\n");
      out.write("        {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background: #ececec;\r\n");
      out.write("            border: 1px solid #ececec;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            height: 120px;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .grade div:first-child \r\n");
      out.write("        {\r\n");
      out.write("            margin: 30px;\r\n");
      out.write("            border-right: 1px solid #404040;\r\n");
      out.write("            padding-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .mypage .grade div:last-child \r\n");
      out.write("        {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .grade div:last-child p strong\r\n");
      out.write("        {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo \r\n");
      out.write("        {\r\n");
      out.write("            margin: 50px 0 50px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .title\r\n");
      out.write("        {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .title h3\r\n");
      out.write("        {\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .title p\r\n");
      out.write("        {\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .title p::before\r\n");
      out.write("        {\r\n");
      out.write("            content: \"*\";\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            color: red;\r\n");
      out.write("            top: 70%;\r\n");
      out.write("            right: 105%;\r\n");
      out.write("            transform: translateY(-50%); \r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1\r\n");
      out.write("        {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 th\r\n");
      out.write("        {\r\n");
      out.write("            border-top: 1px solid #dfdfdf;      \r\n");
      out.write("            padding: 8px 0 8px 0;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(1) th\r\n");
      out.write("        {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(1) th::after\r\n");
      out.write("        {\r\n");
      out.write("            content: \"*\"; \r\n");
      out.write("            position: absolute;          \r\n");
      out.write("            color: red;   \r\n");
      out.write("            top: 35%;\r\n");
      out.write("            left: 20%;         \r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(2) th\r\n");
      out.write("        {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(2) th::after\r\n");
      out.write("        {\r\n");
      out.write("            content: \"*\"; \r\n");
      out.write("            position: absolute;          \r\n");
      out.write("            color: red;   \r\n");
      out.write("            top: 35%;\r\n");
      out.write("            left: 20%;         \r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(3) th\r\n");
      out.write("        {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(3) th::after\r\n");
      out.write("        {\r\n");
      out.write("            content: \"*\"; \r\n");
      out.write("            position: absolute;          \r\n");
      out.write("            color: red;   \r\n");
      out.write("            top: 35%;\r\n");
      out.write("            left: 25%;         \r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(4) th\r\n");
      out.write("        {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(4) th::after\r\n");
      out.write("        {\r\n");
      out.write("            content: \"*\"; \r\n");
      out.write("            position: absolute;          \r\n");
      out.write("            color: red;   \r\n");
      out.write("            top: 35%;\r\n");
      out.write("            left: 38%;         \r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(5) th\r\n");
      out.write("        {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(5) th::after\r\n");
      out.write("        {\r\n");
      out.write("            content: \"*\"; \r\n");
      out.write("            position: absolute;          \r\n");
      out.write("            color: red;   \r\n");
      out.write("            top: 35%;\r\n");
      out.write("            left: 15%;         \r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(6) th\r\n");
      out.write("        {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(6) th::after\r\n");
      out.write("        {\r\n");
      out.write("            content: \"*\"; \r\n");
      out.write("            position: absolute;          \r\n");
      out.write("            color: red;   \r\n");
      out.write("            top: 45%;\r\n");
      out.write("            left: 16%;         \r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(7) th\r\n");
      out.write("        {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(7) th::after\r\n");
      out.write("        {\r\n");
      out.write("            content: \"*\"; \r\n");
      out.write("            position: absolute;          \r\n");
      out.write("            color: red;   \r\n");
      out.write("            top: 35%;\r\n");
      out.write("            left: 25%;         \r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 td\r\n");
      out.write("        {\r\n");
      out.write("            border-top: 1px solid #dfdfdf;\r\n");
      out.write("            padding: 8px 0 8px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(3) td::after\r\n");
      out.write("        {\r\n");
      out.write("            content: \"(비밀번호는 최소 8자 이상이어야 하며, 영문 대소문자, 숫자, 특수문자를 포함해야 합니다.)\";\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 td input\r\n");
      out.write("        {\r\n");
      out.write("            border: 1px solid #d5d5d5;     \r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 5px;    \r\n");
      out.write("            font-size:13px; 	\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(6) td\r\n");
      out.write("        {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(6) input:nth-child(1)\r\n");
      out.write("        {\r\n");
      out.write("            width: 150px;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(6) input\r\n");
      out.write("        {\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            margin: 3px 0;           \r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(6) a\r\n");
      out.write("        {\r\n");
      out.write("            border: 1px solid black;  \r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 30px;  \r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 5px;  \r\n");
      out.write("            background-color: #dfdfdf; \r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin: 3px 0 3px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(6) a:hover\r\n");
      out.write("        {\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(6) input::placeholder\r\n");
      out.write("        {\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(7) th,tr:nth-child(7) td\r\n");
      out.write("        {\r\n");
      out.write("            border-bottom: 1px solid #dfdfdf;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(7) select\r\n");
      out.write("        {\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 27.2px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid #d5d5d5; \r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 tr:nth-child(7) input\r\n");
      out.write("        {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .table1 td input[readonly]\r\n");
      out.write("        {\r\n");
      out.write("        	background-color: #efefef;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .formBtn\r\n");
      out.write("        {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 50px 0 50px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .formBtn .update\r\n");
      out.write("        {\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            width: 120px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            background-color: #2a2b2c;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .formBtn .cancel\r\n");
      out.write("        {\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            width: 120px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            background-color: #84868b;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        .mypage .userInfo .formBtn .delete\r\n");
      out.write("        {\r\n");
      out.write("            float: left;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;   \r\n");
      out.write("            background-color: #dfdfdf;   \r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>헤더</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"normalize.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <div class=\"headerWrap\">\r\n");
      out.write("                <div class=\"banner\">\r\n");
      out.write("                    <section>\r\n");
      out.write("                        <h2>DAEBU EXPRESS</h2>\r\n");
      out.write("                        <div class=\"star star1\"></div>\r\n");
      out.write("                        <div class=\"star star2\"></div>\r\n");
      out.write("                        <div class=\"star star3\"></div>\r\n");
      out.write("                        <div class=\"star star4\"></div>\r\n");
      out.write("                        <div class=\"star star5\"></div>\r\n");
      out.write("                        <div class=\"star star6\"></div>\r\n");
      out.write("                        <div class=\"star star7\"></div>\r\n");
      out.write("                        <div class=\"star star8\"></div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"headerContent\">\r\n");
      out.write("                    <div class=\"left\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("                            <h2>DAEBU</h2>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"center\">\r\n");
      out.write("                        <ul id=\"categoryList\">\r\n");
      out.write("                            <li><a href=\"#\" data-category=\"50\">맨투맨</a></li>\r\n");
      out.write("                            <li><a href=\"#\" data-category=\"40\">후드티</a></li>\r\n");
      out.write("                            <li><a href=\"#\" data-category=\"30\">후드집업</a></li>\r\n");
      out.write("                            <li><a href=\"#\" data-category=\"60\">아우터</a></li>                            \r\n");
      out.write("                            <li><a href=\"#\" data-category=\"20\">코트</a></li> \r\n");
      out.write("                            <li><a href=\"#\" data-category=\"10\">바지</a></li>                          \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"right\">\r\n");
      out.write("                    <!-- 로그인 전 -->\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                     <!--  일반회원 로그인 -->\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                     <!-- 관리자 로그인 -->\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("      \r\n");
      out.write("   	<script>\r\n");
      out.write("		document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("		    var categoryLinks = document.querySelectorAll(\"#categoryList a\");\r\n");
      out.write("		\r\n");
      out.write("		    categoryLinks.forEach(function(link) {\r\n");
      out.write("		        link.addEventListener(\"click\", function(event) {\r\n");
      out.write("		            event.preventDefault();\r\n");
      out.write("		            var categoryNumber = link.getAttribute(\"data-category\");\r\n");
      out.write("		            window.location.href = \"/myapp/product/itemList.do?cate_no=\" + categoryNumber;\r\n");
      out.write("		        });\r\n");
      out.write("		    });\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <div class=\"mypage\">\r\n");
      out.write("        <h2>회원 정보 수정</h2>   \r\n");
      out.write("        <div class=\"grade\">\r\n");
      out.write("            <div><img src=\"https://img.echosting.cafe24.com/skin/base_ko_KR/member/img_member_default.gif\" alt=\"이미지\"></div>\r\n");
      out.write("            <div><p>저희 쇼핑몰을 이용해 주셔서 감사합니다. <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMap.MEM_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>님은 <strong>[");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMap.CK }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("]</strong> 이십니다.</p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"userInfo\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <h3>기본정보</h3>\r\n");
      out.write("                <p>필수 입력 사항</p>   \r\n");
      out.write("            </div>  \r\n");
      out.write("            <form id=\"updateFrm\" onsubmit=\"return validateAndSubmitForm()\">\r\n");
      out.write("                <table class=\"table1\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>아이디</th>\r\n");
      out.write("                        <td><input type=\"text\" name=\"mem_id\" id=\"mem_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>이메일</th>\r\n");
      out.write("                        <td><input type=\"email\" name=\"email\" id=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>비밀번호</th>\r\n");
      out.write("                        <td><input type=\"password\" name=\"mem_pw\" id=\"mem_pw\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_pw }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ></td>                   \r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>비밀번호 확인</th>\r\n");
      out.write("                        <td><input type=\"password\" name=\"mem_pw2\" id=\"mem_pw2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_pw }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>이름</th>\r\n");
      out.write("                        <td><input type=\"text\" name=\"mem_name\" id=\"mem_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>주소</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" name=\"post\" id=\"post\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.post }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"우편번호\">\r\n");
      out.write("                            <a href=\"\">주소검색</a>\r\n");
      out.write("                            <input type=\"text\" name=\"addr1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.addr1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"기본 주소\">\r\n");
      out.write("                            <input type=\"text\" name=\"addr2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.addr2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"나머지 주소\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                        \r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>휴대전화</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <select name=\"mobile1\" id=\"mobile1\">                                                        \r\n");
      out.write("                                <option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mobile1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mobile1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>                             \r\n");
      out.write("                            </select>\r\n");
      out.write("                            \r\n");
      out.write("                            <label for=\"mobile2\">-</label>\r\n");
      out.write("                            <input type=\"text\" id=\"mobile2\" name=\"mobile2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mobile2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"text-align: center;\" required>\r\n");
      out.write("                            <label for=\"mobile3\">-</label>\r\n");
      out.write("                            <input type=\"text\" id=\"mobile3\" name=\"mobile3\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mobile3 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"text-align: center;\" required>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div class=\"formBtn\">\r\n");
      out.write("                	<button class=\"delete\" id=\"delete\" onclick=\"memberDelete()\">회원탈퇴</button>\r\n");
      out.write("                    <button class=\"update\" id=\"update\">회원정보수정</button>\r\n");
      out.write("                    <button class=\"cancel\" id=\"cancel\" onclick=\"goHome()\">취소</button>                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>푸터</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"normalize.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2>DAEBU EXPRESS </h2>\r\n");
      out.write("            <span>\r\n");
      out.write("                <a href=\"#\"><i class=\"xi-instagram\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"xi-facebook-official\"></i></a>\r\n");
      out.write("            </span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container2\">\r\n");
      out.write("            <div class=\"address\">\r\n");
      out.write("                <p>ADDRESS</p>\r\n");
      out.write("                <strong>경기도 안산시 단원구 감나무길 92, 1층 (대부북동)</strong><br>\r\n");
      out.write("                <strong><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/map/map.do\">찾아오시는길</a></strong>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sitePolicy\">\r\n");
      out.write("                <p>SITE POLICY</p>\r\n");
      out.write("                <strong><a href=\"#\" id=\"btn-modal\">TERM OF USE </a></strong>     \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"service\">\r\n");
      out.write("                <p>CUSTOMER SERVICE</p>\r\n");
      out.write("                <strong>TEL : 01063533014</strong><br>\r\n");
      out.write("                <strong>MAIL : lcjh313@google.com</strong>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"modal\" class=\"modal-overlay\">\r\n");
      out.write("        <div class=\"modal-window\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <h2>이용약관</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"close-area\"><i class=\"xi-close\"></i></div>\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("                <p>제1조 (목적)</p>\r\n");
      out.write("                <p>이 약관은 대부 익스프레스(전자상거래 사업자)가<br>\r\n");
      out.write("                   운영하는 대부 익스프레스 사이버 몰(이하 “몰”이라 한다)에서<br>\r\n");
      out.write("                   제공하는 인터넷 관련 서비스(이하 “서비스”라 한다)를 이용함에 있어<br>\r\n");
      out.write("                   사이버 몰과 이용자의 권리․의무 및 책임 사항을 규정함을 목적으로 합니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        /* 모달창의 기본적은 이벤트 */\r\n");
      out.write("        /*\r\n");
      out.write("            1. 특정 버튼을 누르면 모달창이 켜진다.\r\n");
      out.write("            2. 모달창의 클로즈(x) 버튼을 누르면 모달창이 꺼진다.\r\n");
      out.write("            3. 모달창 바깥 영역 (위 그림에서 밝기가 어두운 부분) 을 클릭하면 모달창이 꺼진다.\r\n");
      out.write("            4. 모달창이 켜진 상태에서 ESC 버튼을 누르면 모달창이 꺼진다.\r\n");
      out.write("        */\r\n");
      out.write("\r\n");
      out.write("        const loremIpsum = document.getElementById(\"lorem-ipsum\");\r\n");
      out.write("        fetch(\"https://baconipsum.com/api/?type=all-meat&paras=200&format=html\")\r\n");
      out.write("            .then(response => response.text())\r\n");
      out.write("            .then(result => loremIpsum.innerHTML = result);\r\n");
      out.write("\r\n");
      out.write("            /* 'TERM OF USE' 버튼을 누르면 모달창이 켜지게 하기 */\r\n");
      out.write("            /* 모달의 초기 상태를 display: none;으로 했다가 'TERM OF USE' 버튼을 클릭하면 display: flex; 변경 */\r\n");
      out.write("            const modal = document.getElementById(\"modal\");\r\n");
      out.write("            const btnModal = document.getElementById(\"btn-modal\");\r\n");
      out.write("            btnModal.addEventListener(\"click\", e => {\r\n");
      out.write("                modal.style.display = \"flex\";\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            /* 모달창의 클로즈(x) 버튼을 누르면 모달창이 꺼지게 하기 */\r\n");
      out.write("            const closeBtn = modal.querySelector(\".close-area\");\r\n");
      out.write("            closeBtn.addEventListener(\"click\", e => {\r\n");
      out.write("                modal.style.display = \"none\";\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            /* 모달창 바깥 영역을 클릭하면 모달창이 꺼지게 하기 */\r\n");
      out.write("            modal.addEventListener(\"click\", e => {\r\n");
      out.write("            const evTarget = e.target;\r\n");
      out.write("            if(evTarget.classList.contains(\"modal-overlay\")) {\r\n");
      out.write("                modal.style.display = \"none\";\r\n");
      out.write("                };\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            /* 모달창이 켜진 상태에서 ESC 버튼을 누르면 모달창이 꺼지게 하기 */\r\n");
      out.write("            window.addEventListener(\"keyup\", e => {\r\n");
      out.write("            if(modal.style.display === \"flex\" && e.key === \"Escape\") {\r\n");
      out.write("                modal.style.display = \"none\"\r\n");
      out.write("                 };\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</footer>\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    /* 로그인 체크 */\r\n");
      out.write("    var loginChk = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginChk}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("    \r\n");
      out.write("    if (loginChk == 'fail') {\r\n");
      out.write("        alert(\"로그인 후 이용 가능합니다.\");\r\n");
      out.write("        window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/loginForm.do'; // 리다이렉트\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* 회원정보수정 유효성검사 */\r\n");
      out.write("    $(function() {				\r\n");
      out.write("		$(\"#update\").click(function() {\r\n");
      out.write("            var mem_pw = $(\"#mem_pw\").val();\r\n");
      out.write("            var mem_pw2 = $(\"#mem_pw2\").val();\r\n");
      out.write("            var mobile1 = $(\"#mobile1\").val();\r\n");
      out.write("            var mobile2 = $(\"#mobile2\").val();\r\n");
      out.write("            var mobile3 = $(\"#mobile3\").val();\r\n");
      out.write("			var errorMsg = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("         \r\n");
      out.write("            \r\n");
      out.write("            // 비밀번호 유효성 검사 패턴\r\n");
      out.write("            var pwPattern = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$/;\r\n");
      out.write("            // 비밀번호 최소 길이\r\n");
      out.write("            var minPwLength = 8;\r\n");
      out.write("\r\n");
      out.write("            if(mem_pw == \"\") {\r\n");
      out.write("				alert(\"비밀번호를 입력 하세요.\");\r\n");
      out.write("				$(\"#mem_pw\").focus();\r\n");
      out.write("			} else if(!pwPattern.test(mem_pw)) {\r\n");
      out.write("                alert(\"비밀번호는 최소 8자 이상이어야 하며, 영문 대소문자, 숫자, 특수문자를 포함해야 합니다.\");\r\n");
      out.write("                $(\"#mem_pw\").focus();\r\n");
      out.write("            }  else if(mem_pw2 == \"\") {\r\n");
      out.write("				alert(\"비밀번호 확인을 입력 하세요.\");\r\n");
      out.write("				$(\"#mem_pw2\").focus();\r\n");
      out.write("            } else if(mobile2 == \"\") {\r\n");
      out.write("				alert(\"전화번호를 입력하세요.\");\r\n");
      out.write("				$(\"#mobile2\").focus();\r\n");
      out.write("            } else if(mobile3 == \"\") {\r\n");
      out.write("            	alert(\"전화번호를 입력하세요.\");\r\n");
      out.write("            	$(\"#mobile3\").focus();\r\n");
      out.write("            } else if(mem_pw != mem_pw2) {\r\n");
      out.write("                alert(\"비밀번호가 일치 하지 않습니다.\");\r\n");
      out.write("                $(\"#mem_pw2\").focus();\r\n");
      out.write("            } else if(errorMsg == 'error') {\r\n");
      out.write("            	alert(\"회원 정보를 수정 하던 중 에러가 발생 했습니다.\");         	\r\n");
      out.write("			} else {\r\n");
      out.write("				alert(\"회원 정보를 수정 하였습니다.\");\r\n");
      out.write("				$(\"#updateFrm\").attr(\"action\", \"memberUpdate.do\").attr(\"method\", \"post\").submit();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("    \r\n");
      out.write("    /* 회원탈퇴 */\r\n");
      out.write("    var errorMessage = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   	var errorMsg = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   	\r\n");
      out.write("    function memberDelete() {\r\n");
      out.write("    	if(errorMessage) {\r\n");
      out.write("    		alert(errorMessage);\r\n");
      out.write("    	} else if(errorMsg) {\r\n");
      out.write("    		alert(errorMsg);\r\n");
      out.write("    	} else {\r\n");
      out.write("    		alert(\"정상적으로 회원 탈퇴를 진행 했습니다.\");\r\n");
      out.write("    		$(\"#updateFrm\").attr(\"action\", \"memberDelete.do\").attr(\"method\", \"post\")	\r\n");
      out.write("    	}    	\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write(" 	// 취소 버튼 클릭 시 메인 화면으로 이동\r\n");
      out.write("    function goHome() {\r\n");
      out.write("        window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home'; // 메인 화면으로 이동\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/myPage.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/member/myPage.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/myPage.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path");
      // /WEB-INF/views/member/../include/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/../include/header.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(55,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginMap}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <ul>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginForm.do\">로그인</a></li>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/joinForm.do\">회원가입</a></li>\r\n");
          out.write("                        </ul>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(62,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginMap && loginMap.CODE == '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <ul>\r\n");
          out.write("                        	<li><p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMap.MEM_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write(' ');
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMap.CK}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")님 환영합니다.</p>      \r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/myPage.do\">마이페이지</a></li>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/order/orderList.do?mem_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">주문내역</a></li>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/cart/cart.do?mem_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">장바구니</a></li>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logOut.do\">로그아웃</a></li>\r\n");
          out.write("                        </ul>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(72,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginMap && loginMap.CODE == '1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <ul>  \r\n");
          out.write("                        	<li><p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMap.MEM_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMap.CK}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")님 환영합니다.</p>                        \r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/admin.do\">관리자</a></li>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/productList.do\">상품관리</a></li>\r\n");
          out.write("                            <li><a href=\"\">주문관리</a></li>        \r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logOut.do\">로그아웃</a></li>               \r\n");
          out.write("                        </ul>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/member/../include/footer.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("path");
      // /WEB-INF/views/member/../include/footer.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/../include/footer.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
