/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2024-03-04 13:44:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/gyujin/sideP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shoppiingMall/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/gyujin/sideP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shoppiingMall/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1659671595531L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>상품 관리</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/normalize.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        .product\r\n");
      out.write("        {\r\n");
      out.write("            width: 900px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            background-color: #ececec;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .product h2\r\n");
      out.write("        {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 1.6em;\r\n");
      out.write("        }\r\n");
      out.write("        .product .tableBox\r\n");
      out.write("        {\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border: 1px solid #ececec;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 2px 2px 2px 2px rgba(33, 33, 33, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .product .tableBox table th, td\r\n");
      out.write("        {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .product .tableBox table #prod_name\r\n");
      out.write("        {\r\n");
      out.write("            width: 350px;\r\n");
      out.write("        }\r\n");
      out.write("        .product .tableBox .btn_group\r\n");
      out.write("        {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .product .tableBox .btn_group button:nth-child(1)\r\n");
      out.write("        {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: #c8c8c8;\r\n");
      out.write("        }\r\n");
      out.write("        .product .tableBox .btn_group button:nth-child(2)\r\n");
      out.write("        {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: #e7c64c;\r\n");
      out.write("        }\r\n");
      out.write("        .product .tableBox .btn_group button:nth-child(3)\r\n");
      out.write("        {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: #f7d7d7;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header id=\"header\"></header>\r\n");
      out.write("    <div class=\"product\">\r\n");
      out.write("        <h2>상품 등록</h2>\r\n");
      out.write("        <div class=\"tableBox\">\r\n");
      out.write("            <form action=\"\" name=\"frm\" id=\"frm\" enctype=\"multipart/form-data\">\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>상품명</th>\r\n");
      out.write("                        <td><input type=\"text\" id=\"prod_name\" name=\"prod_name\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>상품 종류</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <select name=\"prod_kind\" id=\"prod_kind\">\r\n");
      out.write("                                <!-- <option value=\"10\">바지</option>\r\n");
      out.write("                                <option value=\"20\">코트</option>\r\n");
      out.write("                                <option value=\"30\">집업</option>\r\n");
      out.write("                                <option value=\"40\">후드</option>\r\n");
      out.write("                                <option value=\"50\">맨투맨</option>\r\n");
      out.write("                                <option value=\"60\">아우터</option> -->\r\n");
      out.write("                                <option value=\"bottom\">바지</option>\r\n");
      out.write("                                <option value=\"coat\">코트</option>\r\n");
      out.write("                                <option value=\"zipup\">집업</option>\r\n");
      out.write("                                <option value=\"hood\">후드</option>\r\n");
      out.write("                                <option value=\"mantoman\">맨투맨</option>\r\n");
      out.write("                                <option value=\"outer\">아우터</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>가격</th>\r\n");
      out.write("                        <td><input type=\"text\" id=\"price\" name=\"price\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>상품 설명</th>\r\n");
      out.write("                        <td><textarea id=\"prod_content\" name=\"prod_content\" rows=\"4\" cols=\"50\"></textarea></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>이미지</th>\r\n");
      out.write("                        <td><input type=\"file\" id=\"prod_image\" name=\"prod_image\" accept=\"image/*\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"btn_group\">\r\n");
      out.write("                <button type=\"button\" id=\"insert\">등록</button>\r\n");
      out.write("                <button type=\"button\" id=\"update\">수정</button>\r\n");
      out.write("                <button type=\"button\" id=\"delete\">삭제</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer id=\"footer\"></footer>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    	var loginChk = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginChk}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("    	\r\n");
      out.write("    	if(loginChk == 'fail') {\r\n");
      out.write("    		alert(\"관리자 로그인 후 이용 가능 합니다.\");\r\n");
      out.write("    		window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/loginForm.do';\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	$(document).ready(function() {\r\n");
      out.write("    	    $(\"#insert\").on(\"click\", function() {\r\n");
      out.write("    	        var prod_name = $(\"#prod_name\").val();\r\n");
      out.write("    	        var selectedOption = $(\"#prod_kind\").val();\r\n");
      out.write("    	        var price = $(\"#price\").val();\r\n");
      out.write("    	        var prod_content = $(\"#prod_content\").val();\r\n");
      out.write("\r\n");
      out.write("    	        // 상품 정보 입력 확인 후 FormData에 상품 정보들을 담는다.\r\n");
      out.write("    	        if(prod_name == \"\") {\r\n");
      out.write("    	            alert(\"상품명을 입력해주세요.\");\r\n");
      out.write("    	            $(\"#prod_name\").focus();\r\n");
      out.write("    	        } else if(selectedOption == \"\") {\r\n");
      out.write("    	            alert(\"상품종류를 선택해주세요.\");\r\n");
      out.write("    	            $(\"#prod_kind\").focus();\r\n");
      out.write("    	        } else if(isNaN(price)) { \r\n");
      out.write("    	            alert(\"가격은 숫자만 입력해주세요.\"); \r\n");
      out.write("    	            $(\"#price\").focus();\r\n");
      out.write("    	        } else if(prod_content == \"\") {\r\n");
      out.write("    	            alert(\"상품내용을 입력해주세요.\");\r\n");
      out.write("    	            $(\"#prod_content\").focus();\r\n");
      out.write("    	        } else {\r\n");
      out.write("    	            // 유효한 경우에만 AJAX 요청 보내기\r\n");
      out.write("    	            var formData = new FormData();\r\n");
      out.write("    	            formData.append('prod_name', prod_name);\r\n");
      out.write("    	            formData.append('prod_kind', selectedOption);\r\n");
      out.write("    	            formData.append('price', price);\r\n");
      out.write("    	            formData.append('prod_content', prod_content);\r\n");
      out.write("\r\n");
      out.write("    	            // AJAX 요청 보내기\r\n");
      out.write("    	            $.ajax({\r\n");
      out.write("    	                url: '/insertProduct.do',\r\n");
      out.write("    	                type: 'POST',\r\n");
      out.write("    	                data: formData,\r\n");
      out.write("    	                processData: false,\r\n");
      out.write("    	                contentType: false,\r\n");
      out.write("    	                success: function(response) {\r\n");
      out.write("    	                    if(response === 'success') {\r\n");
      out.write("    	                        alert('상품 등록이 완료되었습니다.');\r\n");
      out.write("    	                        // location.reload(); \r\n");
      out.write("    	                        window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/productList.do';\r\n");
      out.write("    	                    } else {\r\n");
      out.write("    	                        alert('상품 등록에 실패하였습니다.');\r\n");
      out.write("    	                    }\r\n");
      out.write("    	                },\r\n");
      out.write("    	                error: function() {\r\n");
      out.write("    	                    alert('상품 등록 요청에 실패하였습니다.');\r\n");
      out.write("    	                }\r\n");
      out.write("    	            });\r\n");
      out.write("    	        }\r\n");
      out.write("    	    });\r\n");
      out.write("    	});\r\n");
      out.write("	\r\n");
      out.write("    	\r\n");
      out.write("    	$(document).ready(function() {\r\n");
      out.write("    	    $(\"#frm\").on(\"submit\", function(e) {\r\n");
      out.write("    	        e.preventDefault(); // 기본 이벤트 동작 방지\r\n");
      out.write("\r\n");
      out.write("    	        var formData = new FormData($(this)[0]);\r\n");
      out.write("\r\n");
      out.write("    	        $.ajax({\r\n");
      out.write("    	            url: \"fileUpload.do\",\r\n");
      out.write("    	            type: \"POST\",\r\n");
      out.write("    	            data: formData,\r\n");
      out.write("    	            processData: false,\r\n");
      out.write("    	            contentType: false,\r\n");
      out.write("    	            success: function(response) {\r\n");
      out.write("    	                // 파일 업로드 성공 시 처리\r\n");
      out.write("    	                alert(\"파일 업로드가 완료되었습니다.\");\r\n");
      out.write("    	                window.location.href = \"/admin/productList.do\";\r\n");
      out.write("    	            },\r\n");
      out.write("    	            error: function(xhr, status, error) {\r\n");
      out.write("    	                // 파일 업로드 실패 시 처리\r\n");
      out.write("    	                alert(\"파일 업로드에 실패하였습니다.\");\r\n");
      out.write("    	                console.log(xhr.responseText);\r\n");
      out.write("    	            }\r\n");
      out.write("    	        });\r\n");
      out.write("    	    });\r\n");
      out.write("    	});\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/admin/productFile.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/admin/productFile.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/productFile.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
